const pageContent = {
  "translations": {
    "en": {
      "nav.reise": "The Journey",
      "reise.hero_title": "THE JOURNEY",
      "reise.hero_subtitle": "Deep TCM Immersion & Daoist Retreat in China",
      "reise.hero_dates": "October 10 – 20, 2026 | 10 Days, 10 Nights",
      "reise.overview_title": "Part 1: TCM Intensive Training in Shenzhen",
      "reise.overview_desc": "Over these five days, Master Xu Ruqi and his team will lead us through a balance of both TCM theory and practice. You will learn principles of TCM from a cultural, medical, and historical spiritual lens, whilst also witnessing live patient treatments. This will all take place in his newly opened hospital and school in the heart of the city.",
      "reise.wudang_title": "Part 2: Integration into Sacred Rural Life in China",
      "reise.wudang_desc": "On October 15th, we travel to the Wudang Mountains, a legendary Daoist landscape where the spirals of yin and yang are said to meet. We will stay at the private rural residence of Daoist Priest Yin Chen Zi and his wife Li Xin, sharing organic, home-cooked meals and daily life in close connection with the land. Within this intimate setting, we deepen our practice through traditional methods.",
      "reise.itinerary_title": "The Itinerary",
      "reise.day_arrival": "October 09 | Arrival Day",
      "reise.day_arrival_desc": "Arrive in Shenzhen & Check-in at Hotel Qianhai Gongyu. Private room for each participant. Dinner in the evening together.",
      "reise.day_prep": "October 10 | Welcome & Preparation",
      "reise.day_prep_desc": "Orientation & group introduction. Opening meditation, hypnosis, and sound session. Master Xu's individual diagnosis for each participant and personalized herbal medicine prescriptions.",
      "reise.day_tcm": "October 10 – 14 | TCM Intensive Training",
      "reise.day_tcm_desc": "4 days of immersive learning & practice. Core topics include Historical Insights, Pulse & Tongue Diagnosis, Yin-Yang Theory, and live patient treatment observations.",
      "reise.day_wudang": "October 15 – 20 | Wudang Mountains Integration",
      "reise.day_wudang_desc": "Travel to Wudang. Living in the sanctuary of the original source of Qi. Excursions to cultural sites, Daoist temples, traditional tea ceremonies, and optional treatments (Moxibustion, Cupping, Gua Sha).",
      "reise.pricing_title": "Pricing & Payment Plans",
      "reise.pricing_subtitle": "Choose the right plan for your journey",
      "reise.price_earlybird": "Early Bird",
      "reise.price_earlybird_desc": "Valid till May 31st",
      "booking.popular": "Most Popular",
      "reise.price_standard": "Standard Price",
      "reise.price_standard_desc": "Regular booking rate",
      "reise.price_couple": "Couple Deal",
      "reise.price_couple_desc": "For two participants",
      "booking.contact_us": "Contact Us to Book",
      "reise.inclusions": "Includes: Accommodation, meals, classes, domestic train to Wudang. <br>Excludes: International flights & Visa.",
      "nav-home": "Home",
      "nav-about": "About & Masters",
      "nav-treatments": "Health Maintenance",
      "nav-devices": "Technology",
      "nav-programs": "Programs",
      "nav-retreat": "Retreat",
      "nav-info": "Clinic Info",
      "nav-apply": "Register",
      "hero-tag": "Traditional Chinese Medicine meets Modern Medical Technology",
      "hero-title": "Traditional Chinese Medicine & Clinical Diagnostics",
      "hero-desc": "Experience deep physical and spiritual transformation through the 40-year TCM expertise of Professor Xu Ruqi, individualized herbal therapies, cutting-edge diagnostic devices, and healing sound ceremonies.",
      "hero-cta-apply": "Register Now",
      "hero-cta-more": "Explore Programs",
      "intro-title": "Ancient Formulas as Foundation, Technology as Wings",
      "intro-desc": "<p style=\"margin-bottom: 1rem;\">The Hong Dao Clinic was founded by a team of renowned experts of the SHANGHANLUN 伤寒论 tradition of the ascended Master ZHANG Zhongjing 张仲景 and doctoral graduates of Fudan University, combining classical Chinese herbal formulas with modern technology and diagnostic methods.</p><p style=\"margin-bottom: 1rem;\">Under the guiding principle “Ancient Formulas as Foundation, Technology as Wings”, the clinic unites research and teaching in an integrative concept serving people worldwide.</p><p>We offer individually tailored care and treatment plans for patients suffering from complex conditions such as autoimmune disorders, metabolic diseases like diabetes, endometriosis, hormonal imbalances, chronic fatigue, cancer, and infertility.</p>",
      "team-tag": "Medical Lineage",
      "team-title": "Guardians of Ancient Wisdom & Specialized Clinicians",
      "team-subtitle": "Meet our dedicated doctors and practitioners bridging classical Shanghanlun wisdom and modern recovery.",
      "master-xu-title": "Chief Physician & TCM Professor",
      "master-xu-desc": "Professor Xu Ruqi has spent over 40 years mastering pulse diagnosis and classical herbal medicine. A clinical expert at Beijing University of Chinese Medicine, he is globally renowned for treating severe chronic conditions, advanced tumors, and gynecological diseases.",
      "doctor-1-title": "Clinic Director & Stem Cell Therapy",
      "doctor-1-name": "Dr. Qiao Jingwen <span style=\"white-space: nowrap;\">(乔靖文)</span>",
      "doctor-1-desc": "Dr. Qiao Jingwen is Director of the Hong Dao Clinic, combining cutting-edge stem cell therapy with TCM rejuvenation techniques for cellular health, fertility, and hormonal balance.",
      "doctor-4-name": "Dr. Guan Weina (管蔚娜)",
      "doctor-4-spec": "Licensed TCM Physician. Specialist in meridian detoxification, clinical acupuncture, and therapeutic massages.",
      "doctor-5-name": "Dr. Zhang Hailin (张海林)",
      "doctor-5-spec": "Head of Decoction Center. Expert in traditional herbal extraction and quality control.",
      "btn-read-bio": "Read Profile",
      "decoction-subtitle": "In-House Herbal Craftsmanship",
      "decoction-title": "Modern Decoction Center & Dao Di Herbs",
      "decoction-desc": "<p style=\"margin-bottom: 1.5rem;\">We source exclusively high-quality <strong>Dao Di Herbs (道地藥材)</strong> from certified organic cultivation and soil-specific farming methods, grown in regions that offer the optimal climatic and energetic conditions for each native plant.</p><p>In our in-house Decoction Center, under the direct supervision of Master Xu, these herbs are individually extracted, precisely processed, and portion-packed into <strong>Ready-to-Drink decoctions</strong> that you can easily take home.</p>",
      "visionary-deng-title": "Heilpraktikerin, Qi Gong & Sound Therapy",
      "visionary-deng-desc": "Heilpraktikerin Deng Nanjing translates Professor Xu's consultations into German, English, Italian, Spanish, and Mandarin. She also leads Qi Gong sessions, 6 Healing Sounds practice, sound therapy, tea ceremonies, and supports guests with all organizational needs during their stay.",
      "visionary-deng-spec": "Heilpraktikerin, Qi Gong, Sound Therapy & Patient Support. 5 Languages.",
      "team-grid-title": "Our Specialized Team",
      "doctor-3-name": "Dr. Chen Kainan (陈恺楠) — Assistant Physician",
      "doctor-3-spec": "Assistant Physician, specializing in acupuncture and clinical support under Professor Xu's guidance.",
      "doctor-sound-name": "Cheung Mingli (张明丽)",
      "doctor-sound-spec": "Founder of Voice Alchemy, International Sound Healing & Voice Activation Facilitator with 10+ years of experience.",
      "treatments-title": "Health Maintenance Fields",
      "treatments-subtitle": "Tailored, highly focused strategies for targeted recovery.",
      "treatment-1-title": "Endometriosis & Women's Health",
      "treatment-1-desc": "Custom herbal pastes, womb massage, and acupressure to dissolve blood stagnation and relieve chronic pain.",
      "treatment-2-title": "Stem Cell & Longevity",
      "treatment-2-desc": "Dr. Adrianna Qiao integrates advanced cellular research with TCM health maintenance for cellular health.",
      "treatment-3-title": "Stress & Burnout Recovery",
      "treatment-3-desc": "Holistic relief for high-pressure lifestyles using pulse-guided acupuncture and relaxing sound frequencies.",
      "devices-title": "Advanced Health Maintenance Technology",
      "devices-subtitle": "Traditional diagnostic wisdom validated by high-end modern devices.",
      "device-1-name": "Infrared Body Scan",
      "device-1-desc": "Visualizes inflammation, circulation blockages, and energy paths using 5th gen HD thermal imaging.",
      "device-1-uses": "Primary uses: Spine & neck disorders, metabolic health, inflammation tracking, blood circulation.",
      "device-2-name": "Bian Hu Bioelectric Therapy",
      "device-2-desc": "Combines heated Bian stone pot massage with low & medium frequency bioelectric regulation.",
      "device-2-uses": "Primary uses: Shoulder pain, cervical vertebra, intervertebral disc herniation, gastrointestinal conditioning, endometriosis (PCOS/PMOS).",
      "device-3-name": "Herbal Thermal Moxibustion",
      "device-3-desc": "Patented down-burning moxibustion box for large-scale spine warming with ginger and herbs.",
      "device-3-uses": "Primary uses: Cold womb & dysmenorrhea, cold waist & knees, gynecological inflammation, spine disorders.",
      "device-4-name": "Thermal Metabolic Cabin",
      "device-4-desc": "Whole-body spectrum cabin using far-infrared, oxygen enrichment, and negative ions for cellular health.",
      "device-4-uses": "Primary uses: Athletic recovery, reproductive health, chronic disease conditioning, metabolic detox.",
      "device-5-name": "Micro-Photon Moxibustion",
      "device-5-desc": "Cantilever spectrum radiator emitting 560-1400nm wavelengths to penetrate 7-10cm deep into tissue.",
      "device-5-uses": "Primary uses: Anti-inflammatory & pain relief, joint pain, post-burn skin repair, cosmetic treatments, arthritis, sports injuries.",
      "endo-details-link": "View Details",
      "programs-title": "Health Programs & Training",
      "programs-subtitle": "From intensive training courses to customized personal health maintenance retreats.",
      "retreat-10day-title": "10-Day Teacher Training & Retreat",
      "retreat-10day-date": "October 10th - October 20th, 2026",
      "retreat-10day-desc": "A complete immersion in TCM theory and health maintenance. 5 days of clinical observation in Shenzhen under Master Xu, followed by 5 days of Daoist lifestyle integration in the Wudang Mountains. Limited to 12 participants.",
      "retreat-10day-price": "€3,900 Cost Contribution (Early Bird)",
      "retreat-10day-wix-link": "View Details",
      "retreat-1day-title": "1-3-5 Day TCM Clinical Training (Shenzhen)",
      "retreat-1day-desc": "Focused clinical training and masterclasses in Shenzhen. Ideal for practitioners and health enthusiasts wishing to experience direct clinical practice observation, pulse diagnosis introduction, and professional decoction preparation. Flexible attendance from 1 to 5 days.",
      "retreat-1day-price": "€250 first day, €200 each additional day",
      "endo-program-title": "Endometriosis Health Maintenance Program",
      "endo-program-desc": "A dedicated, fully customizable program addressing uterine health, hormone balance, and pain relief. Features customized herbal formulas, womb massage, sound healing, and direct guidance.",
      "endo-select-duration": "Select Program Duration:",
      "endo-btn-book": "Book & Pay Direct (Stripe)",
      "endo-btn-inquire": "Inquire / Apply",
      "duration-1w": "1 Week",
      "duration-2w": "2 Weeks",
      "duration-4w": "4 Weeks",
      "endo-price": "Price on request",
      "package-basic": "Outpatient (No Boarding)",
      "package-premium": "Premium Retreat (With Partner Hotel & TCM Kitchen)",
      "endo-included-title": "What's Included:",
      "endo-price-note": "*Note: Cost contributions exclude individually prescribed customized herbal medicines.",
      "yunnan-title": "Mountain Retreats & Nature Extension",
      "yunnan-subtitle": "A mystical transition from the city clinic into pristine mountain elements.",
      "yunnan-desc-1": "Extend your clinical program with a nature retreat. Every treatment plan, training course, and retreat begins with intensive diagnosis and therapy at our Shenzhen clinic, after which you travel directly to China's pristine mountain sanctuaries.",
      "yunnan-desc-2": "The second, immersive part always takes place in a beautiful location in the mountains of China. We have a traditional guesthouse operated by Daoist Master Yin Chen Zi and his wife in the Wudang Mountains, as well as accommodations in Wuyi Shan and Yunnan (Xishuangbanna).",
      "yunnan-hotel-info": "Accommodations include: Traditional wood guesthouse in Wudang (Master Yin Chen Zi), scenic mountain lodging in Wuyi Shan, and the high-end luxury Yunnan Horizon Sanctuary eco-resort.",
      "yunnan-meta-title": "Hong Dao TCM Clinic | Yunnan Tea, Mushroom & Herb Culture Journey",
      "yunnan-meta-desc": "Intensive nature, healing, and cultural experience in the mountains of Yunnan. Discover ancient tea forests, medicinal mushrooms, TCM, and ethnic minorities.",
      "yunnan-page-hero-tag": "6-Day Yunnan Culture Journey & Retreat",
      "yunnan-page-hero-title": "YUNNAN RETREAT",
      "yunnan-page-hero-subtitle": "6-Day Tea, Mushroom & Herb Culture Journey with Ethnic Minorities",
      "yunnan-page-header": "Awakening the Life Force",
      "yunnan-page-subheader": "A transformative journey into China's pristine nature",
      "yunnan-page-intro": "This journey is an intensive nature, healing, and cultural experience in the mountains of Yunnan. It connects the wisdom of Taoism, Traditional Chinese Medicine (TCM), medicinal mushrooms, ancient tea cultures, and the life of local minority groups (primarily the Hani) into a deep path of regeneration and self-discovery.",
      "yunnan-page-core-idea-title": "The Core Idea",
      "yunnan-page-core-idea-desc": "At the center lies the reawakening of the \"Life Force\" (生命原力) – that natural energy which, according to Taoist and Chinese medicine, nourishes health, creativity, vitality, and inner clarity.",
      "yunnan-page-transform-title": "The Three-Stage Transformation Process:",
      "yunnan-page-transform-1": "<strong>1. Jing (Essence) – Creating the Foundation:</strong> Physical regeneration, building energy and resources, nutrition, medicinal herbs, and healing mushrooms.",
      "yunnan-page-transform-2": "<strong>2. Qi (Life Energy) – Activating & Transforming:</strong> Breathwork, Taoist practices, movement and energy work, opening and harmonizing the meridians.",
      "yunnan-page-transform-3": "<strong>3. Shen (Spirit) – Refinement & Awareness:</strong> Meditation, sound healing, inner clarity and emotional balance, connection with one's inner core.",
      "yunnan-page-experts-title": "Expert Guidance",
      "yunnan-page-experts-desc": "During the entire trip, the group is accompanied by:",
      "yunnan-page-expert-1": "A renowned TCM Master for pulse and tongue diagnosis",
      "yunnan-page-expert-2": "A TCM Physician and health coach",
      "yunnan-page-expert-3": "An internationally certified Sound Therapist",
      "yunnan-page-expert-4": "Local mushroom experts from the Hani minority",
      "yunnan-page-expert-5": "Tea farmers and herbalists from the mountains of Yunnan",
      "yunnan-page-experts-note": "Every participant receives an individual TCM diagnosis with personalized recommendations for herbs, nutrition, and lifestyle.",
      "yunnan-page-experience-title": "What Participants Experience",
      "yunnan-page-exp-nervous-title": "Arriving & Regulating the Nervous System",
      "yunnan-page-exp-nervous-desc": "The journey begins with a festive opening ceremony, breathwork, sound healing, group resonance work, a Blue Lotus tea ceremony, and intention setting. The goal is to shift the nervous system from stress mode into regeneration mode.",
      "yunnan-page-exp-forest-title": "Discovering Ancient Tea Forests & Medicinal Mushrooms",
      "yunnan-page-exp-forest-desc": "A highlight is the trek through the ancient tea forests of Nan Nuo Shan, one of Yunnan's oldest Pu-erh tea regions. There, participants encounter tea trees up to 800 years old, wild medicinal herbs, traditional herbal lore, and medicinal mushroom hunting with Hani guides. Mushrooms and herbs collected and explained include: <strong>Reishi (Lingzhi), Poria (Fu Ling), Red Wild Mushroom (Da Hong Jun), Puffball Mushrooms (Ma Bo), Dendrobium, Polygonatum, Angelica Root</strong>, and other mountain herbs. Participants not only learn about their therapeutic benefits but also create their own medicinal mushroom and herb identification cards.",
      "yunnan-page-exp-ethnicity-title": "Living with the Yunnan Minority Tribes",
      "yunnan-page-exp-ethnicity-desc": "A unique aspect of this journey is direct contact with local ethnic communities. Participants learn traditional mushroom harvesting, tea processing, local healing practices, traditional diets, and the deep spiritual nature-connectedness of the mountain peoples. This offers an authentic glimpse into a way of life that has been intimately connected to the forest, mountains, and seasons for centuries.",
      "yunnan-page-exp-daoist-title": "Taoist Practice & Nourishing Life (Yang Sheng)",
      "yunnan-page-exp-daoist-desc": "Daily sessions include Qi Gong, Taoist breathing techniques, meditation, body awareness exercises, energy work, and techniques for hormonal and emotional regulation. These practices are designed to reduce stress, activate the Vagus nerve, improve sleep quality, harmonize the endocrine system, and stimulate self-healing capacities.",
      "yunnan-page-exp-sound-title": "Sound Healing & Inner Transformation",
      "yunnan-page-exp-sound-desc": "Another focal area consists of deep sound and frequency journeys: vocal work, mantra meditation, healing frequencies, elements of trance and hypnosis, and \"Tree of Life\" sound journeys. The work with sound is intended to synchronize heart rate, breathing, and brain waves, facilitating profound relaxation.",
      "yunnan-page-target-title": "Who This Journey is For",
      "yunnan-page-target-desc": "Ideal for individuals who are under chronic stress, wish to prevent fatigue or burnout, want to strengthen their health holistically, are interested in TCM, medicinal mushrooms, and tea culture, seek a deeper connection to nature, or wish to experience Taoist lifestyle arts.",
      "yunnan-page-essence-title": "Essence of the Journey",
      "yunnan-page-essence-desc": "This journey is far more than a retreat. It is an encounter with the ancient tea forests of Yunnan, the medicinal mushrooms of the mountain woods, the wisdom of minority peoples, and the Taoist paths for cultivating body, energy, and mind. You do not just learn about tea, mushrooms, and herbs – you experience directly how nature, traditional healing arts, and inner practice work together to re-ignite vitality, peace, and the joy of living.",
      "child-title": "Hong Dao Child Space",
      "child-desc": "We believe family healing involves the youngest. Our clinic hosts a beautiful internal Children's Space, providing peaceful activities, kids TCM nutrition guidance, and regular public and internal events for families to connect.",
      "info-title": "Practical Clinic Information",
      "info-location-label": "Location & Access",
      "info-location-desc": "Hong Dao TCM Clinic, Shenzhen Nanshan District. Easily reachable via metro and highway.",
      "info-hours-label": "Opening Hours",
      "info-hours-desc": "Monday - Saturday: 09:00 - 18:00 (Appointments Required)",
      "info-payment-label": "Registration & Cost Contribution Policy",
      "info-payment-desc": "Online registration is available. Please note your registration is officially confirmed only upon receipt of your personalized confirmation email. All contributions go directly toward covering the costs of the clinic's health programs.",
      "faq-title": "Frequently Asked Questions",
      "faq-q1": "Are customized herbal medicines included in the cost contribution?",
      "faq-a1": "No. Individually prepared herbal formulas for home use are provided separately to compensate for the direct preparation costs according to diagnostic needs.",
      "faq-q2": "How is the Yunnan travel organized?",
      "faq-a2": "Our team coordinates transfer assistance. The program covers the local partner hotel stay, guidance, and specified activities.",
      "faq-q3": "Can I bring my family?",
      "faq-a3": "Yes. Our Hong Dao Child Space offers family-friendly support and special weekend activities for children while parents undergo therapies.",
      "faq-q4": "Do I need a visa for China?",
      "faq-a4": "Most EU citizens (incl. Germany, Austria, Switzerland) can enter China visa-free for up to 30 days since 2024. Please verify the current entry requirements for your country before departure.",
      "faq-q5": "Which apps do I need in China?",
      "faq-a5": "<strong>Install before departure:</strong><br>&#8226; <strong>WeChat</strong> &#8211; Communication (China's WhatsApp)<br>&#8226; <strong>Alipay</strong> &#8211; Payment (link your credit card!)<br>&#8226; <strong>Didi</strong> &#8211; Taxi booking<br>&#8226; <strong>AMap</strong> &#8211; Navigation<br>&#8226; <strong>VPN</strong> &#8211; e.g. Jamjams or Potatso Lite",
      "faq-q6": "How does payment work on site?",
      "faq-a6": "China is almost entirely cashless. Download <strong>Alipay</strong> and link your credit card (Visa/Mastercard). You can pay everywhere with it.",
      "faq-q7": "What can I expect from a TCM treatment?",
      "faq-a7": "Professor Xu creates an individual diagnosis via pulse diagnostics and tongue analysis. Treatment typically includes herbal formulas, acupuncture, and moxibustion. Initial improvements often appear after 1-2 weeks, sustainable changes after 4+ weeks.",
      "contact-tab-calendly": "📅 Book Appointment Online",
      "contact-tab-form": "✉️ Application Form",
      "contact-title": "Begin Your Healing Journey",
      "contact-subtitle": "Contact us or register directly for your customized program.",
      "contact-free-consult": "Request a Free 15-Min Consultation",
      "contact-free-desc": "Speak directly with Nanjing Deng to discuss your symptoms and select the ideal health maintenance path.",
      "contact-label-name": "Full Name",
      "contact-label-email": "Email Address",
      "contact-label-phone": "Phone Number",
      "contact-label-program": "Program of Interest",
      "contact-label-date": "Select Consultation Date (Wed & Sat)",
      "contact-label-slot": "Select Time Slot (Chinese Time 14:00 - 20:00)",
      "contact-label-message": "Brief Medical History / Notes",
      "contact-submit-btn": "Register Now",
      "contact-submit-email": "Register via Email",
      "contact-submit-whatsapp": "Register via WhatsApp",
      "contact-social-text": "Connect with us on Social Media for daily health tips, sound circles and tea recipes:",
      "whatsapp-text": "Chat on WhatsApp",
      "instagram-text": "Instagram: nanjing_tea.sound",
      "booking-success-toast": "Registration submitted! Check your email inbox for confirmation.",
      "card-select-start-date": "Select Start Date:",
      "contact-label-start-date": "Desired Program Start Date",
      "popup-title": "Welcome Offer",
      "popup-desc": "Register today for our Endometriosis Programs or the Wudang Retreat and receive a 10% reduction on the cost contribution for your initial consultation.",
      "popup-code-label": "Your Registration Code:",
      "popup-cta": "Register with Code",
      "treatment-4-badge": "Mycology",
      "treatment-4-title": "Fungal Medicine & Mycelial Regulation",
      "treatment-4-desc": "Unblocking membranous pathways (膜络) using medical macrofungi (Poria, Reishi, Cordyceps). Supports regression of breast and thyroid nodules and regulates the vegetative nervous system.",
      "nav-resources": "Resources",
      "resources-tag": "Knowledge & Downloads",
      "resources-title": "Clinic Manuals & Science",
      "resources-subtitle": "Download official manuals of our clinical devices and deepen your understanding of our treatment systems.",
      "wisdom-tag": "WeChat Wisdom & Clinical Practice",
      "wisdom-title": "The Wisdom of Fungal Medicine: From Soil to Membrane",
      "wisdom-text": "<p style=\"margin-bottom: 1rem;\">Beneath the earth lies a neural network – the 'Wood Wide Web'. Just like this planetary immune system, mushrooms work in our bodies through symbiosis and regulation. They connect with our '膜络' (membranous collaterals) to clear blockages, transform dampness, and resolve nodules (cysts, fibroids, thyroid nodules).</p><p>In our clinical practice, we combine these natural laws with modern care. Read the full scientific report by Dr. Zhang Hailing and Dr. Chen Kainan.</p>",
      "wisdom-link": "Read Original Article (WeChat)",
      "cases-title": "Clinical Case Studies",
      "case-1": "<strong>Case 1 (Thyroid Nodules, 2.1cm):</strong> Complete symptom relief and nodule regression to 0.9cm after 3 months of Poria & Ganoderma therapy.",
      "case-2": "<strong>Case 2 (Breast Hyperplasia & Anxiety):</strong> Dispersal of breast nodules (1.6cm) and relief of palpitations/insomnia through mycelial regulation.",
      "download-program-brochure": "Download Retreat Book (PDF)",
      "manuals-grid-title": "Medical Device Manuals & Brochures",
      "pdf-1-title": "Spectrum Treatment Device 2.0",
      "pdf-1-desc": "Detailed clinical manual on thermal spectrum light therapy for cellular rejuvenation and meridian warming.",
      "pdf-2-title": "Pian-Stone Medium-Frequency Pot 2.0",
      "pdf-2-desc": "Operation manual and applications of the warm Pian-stone electrotherapy device for meridian massage.",
      "pdf-3-title": "Infrared Thermal Imaging 4.0",
      "pdf-3-desc": "Guide to infrared thermal imaging diagnostics for visualizing inflammation and microcirculation patterns.",
      "pdf-4-title": "铺灸 / Pu Jiu Moxibustion Manual 3.1",
      "pdf-4-desc": "Clinical protocols for spine moxibustion (Pu Jiu) to expel deep body cold and nourish Yang vitality.",
      "pdf-5-title": "Frequency Hyperthermia Cabin 3.5",
      "pdf-5-desc": "Therapeutic manual for the clinical hyperthermia cabin, optimizing cellular detox and metabolic fire.",
      "pdf-6-title": "Dao-Pilz-Retreat Program Guide",
      "pdf-6-desc": "Full program details and daily schedules for the Daoist Mushroom Retreat in the Wudang Mountains.",
      "pdf-download-btn": "Download PDF",
      "treatment-1-badge": "Gynecology",
      "treatment-2-badge": "Cell Therapy",
      "treatment-3-badge": "Neurology",
      "nav-tech-btn": "TCM Technology",
      "tech-modal-title": "Clinical Technology & Therapy Methods",
      "tech-download-manual": "Download Manual (PDF)",
      "tech-device-2-title": "Bian Stone Electro-Frequency Therapy",
      "tech-device-2-long-desc": "Combines Bian stone physical properties with target electrical frequencies to stimulate cellular metabolism and relieve muscle-skeletal tension.",
      "tech-device-3-title": "Large-Scale Moxibustion (Pu Jiu)",
      "tech-device-3-long-desc": "A thermal therapy applied over large body zones (such as the back) burning mugwort to warm the meridians, boost Yang energy, and regulate immunological response.",
      "tech-device-4-title": "Whole-Body Spectrum Cabin",
      "tech-device-4-long-desc": "Utilizes a broad electromagnetic wavelength spectrum to warm body tissues. Promotes peripheral microcirculation, supports cellular drainage, and alleviates chronic muscle stiffness.",
      "tech-device-5-title": "Localized Spectrum treatment radiator",
      "tech-device-5-long-desc": "Targeted spectrum radiation simulating natural body emission frequencies to stimulate tissue regeneration, local metabolism, and complement classical acupuncture treatments.",
      "read-details-btn": "Read Details",
      "gallery-title": "Impressions from our last Retreat 2025",
      "gallery-more-btn": "More Photos",
      "gallery-subtitle": "Photos and moments of group training, meditations, and nature experiences.",
      "gallery-item-group-badge": "Group",
      "gallery-item-group-title": "Retreat Group 2025",
      "gallery-item-meditation-badge": "Meditation",
      "gallery-item-meditation-title": "Sound Meditation",
      "gallery-item-qigong-badge": "Qi Gong",
      "gallery-item-qigong-title": "Morning Qi Gong",
      "gallery-item-tea-badge": "Ceremony",
      "gallery-item-tea-title": "Tea Ceremony",
      "gallery-item-lecture-badge": "Lecture",
      "gallery-item-lecture-title": "Pulse Diagnosis",
      "gallery-item-nature-badge": "Nature",
      "gallery-item-nature-title": "Hiking & Herbs",
      "gallery-item-practice-badge": "Practice",
      "gallery-item-practice-title": "Moxa Training",
      "gallery-item-kitchen-badge": "Nutrition",
      "gallery-item-kitchen-title": "Healing Kitchen",
      "gallery-item-soundbath-badge": "Sound Bath",
      "gallery-item-soundbath-title": "Nature Sound Bath",
      "btn-read-article": "Read Article",
      "btn-read-details": "View Details",
      "endo-read-approach": "Treatment Approach & Case Studies",
      "footer-impressum": "Impressum / Legal Notice",
      "footer-privacy": "Privacy Policy",
      "contact-wechat-wrapper": "<strong>WeChat:</strong> <a href=\"#\" class=\"read-article-btn\" data-article=\"wechat\" style=\"color: var(--terracotta); text-decoration: underline; font-weight: 500;\">Show QR Codes</a>",
      "endo-meta-title": "Hong Dao TCM Clinic | Endometriosis Program",
      "endo-page-hero-tag": "Endometriosis Program",
      "endo-page-title": "A Journey Back to Your Origin",
      "endo-page-subtitle": "Holistic Support for Women with Endometriosis in China",
      "endo-page-header": "Your body is not fighting against you.<br><span style=\"font-size: 1.5rem; color: var(--text-dark);\">Perhaps it is time to stop fighting against it.</span>",
      "endo-page-intro": "<p>Come with us to China.</p><p>To the roots of a medicine that has understood the language of the female body for millennia.</p><p>To the misty mountains of Yunnan.</p><p>To peace, acceptance, sisterhood, and new hope.</p><p>And perhaps a step closer to your feminine essence.</p>",
      "endo-page-body-1": "<p>Perhaps you have already come a long way.</p><p>Perhaps your pain has been suppressed with hormones, perhaps you have already undergone surgeries, or you have been told that further interventions are inevitable. Many women with endometriosis live for years between symptom management, uncertainty, and the feeling that their body is working against them.</p><p><strong>But what if your body is not your opponent?</strong></p><p>What if the pain, exhaustion, inflammation, and cycle complaints speak a language that wants to be understood?</p><p>In Traditional Chinese Medicine, we do not view endometriosis as an isolated disease, but as an expression of a deeper imbalance. Instead of suppressing symptoms, we ask: Why has the body fallen out of balance? What does it want to tell us? And how can we support it to return to its natural order?</p>",
      "endo-page-quote": "<p style=\"margin-bottom: 1rem;\">In a time when more and more women are looking for natural and holistic paths, China opens the door to thousands of years of knowledge that does not view the female body as a problem/object, but as an intelligent system striving for balance.</p><p style=\"font-weight: 600;\">Where modern medicine often asks, \"What do we need to remove?\", Chinese Medicine asks, \"What do we need to nourish so that the body finds its way back to its natural order?\"</p>",
      "endo-week1-title": "Week 1: The Shenzhen Clinic",
      "endo-week1-desc": "<p>Our journey begins in Shenzhen, where we spend the first week in our experienced TCM clinic. Through comprehensive diagnostics, we create an individual treatment plan tailored to your personal history, complaints, and constitution.</p><p>We look not only at physical symptoms but also at nutrition, lifestyle, stress, emotional strain, and the deeper patterns that may have contributed to the condition. Together we develop a sustainable path that will continue to support you even after the journey.</p><p>During this first week, we already begin your individual herbal therapy. In addition, we utilize modern biomedical methods such as the BianHu Bio-Electric Resonance Massage and other supportive technologies that can help stimulate blood circulation, tissue nourishment, and the body's natural regulatory processes.</p>",
      "endo-page-poetic": "<p>Chinese medicine speaks of 血海 (Xuè Hǎi) – the Sea of Blood, of 衝脈 (Chōng Mài) – the Sea of Femininity and Fertility, of 子宮 (Zǐ Gōng) – the Palace of the Child. The language alone shows a deeply rooted reverence for the female body.</p><div class=\"endo-poetic-highlight\"><p>The womb is not an organ to be fought against.<br><strong>It is a palace.</strong></p><p style=\"margin-top: 1rem;\">The cycle is not a problem.<br><strong>It is a rhythm.</strong></p><p style=\"margin-top: 1rem;\">Menstruation is not a tedious side effect.<br><strong>It is a message.</strong></p></div>",
      "endo-week2-title": "Week 2: Deep Transformation in Yunnan",
      "endo-week2-desc-1": "<p>After the first week, we travel together into the magical nature of Yunnan. Surrounded by misty mountains, ancient forests, and the peace of rural China, we spend our time in a beautiful 5-star hotel, far from the noise and hectic pace of everyday life.</p><p>Here begins the deeper healing journey.</p><p>In China, we experience not only the medicine but also the wisdom of a culture that is increasingly turning back to its traditional roots. Back to nature. Back to cycles. Back to the connection between human and earth.</p>",
      "endo-week2-poetic": "This second phase of the journey is dedicated to Yin.<br>To nourishing.<br>To receiving.<br>To letting go.<br>To remembering.",
      "endo-week2-desc-2": "<p>Many women with endometriosis have learned over years to fight, endure, and function. Here you can experience what it feels like to stop working against your body, and instead work with it.</p><p>Through sufficient sleep, deep relaxation, nourishing food, gentle movement, Qi Gong, breathwork, meditation, and plenty of time in nature, we create the conditions where recovery becomes possible in the first place.</p><p>We relearn what it means as a woman to live with the natural rhythms of life – with ebb and flow, activity and rest, Yang and Yin.</p><p>Throughout the entire journey, we continue the herbal therapy and observe together the changes on physical, emotional, and energetic levels. You will be carried and supported by an experienced team.</p>",
      "endo-page-cta-text": "This journey is not a promise of healing.<br>It is an invitation.<br>An invitation to discover a different path.<br>A path based not on suppression, but on understanding.<br>Not on fighting, but on cooperation.<br>Not on separation, but on reconnection.<br><br>A journey back to your body.<br>Back to your femininity.<br>Back to your origin.",
      "endo-page-cta-btn": "Schedule a Consultation"
    },
    "de": {
      "nav.reise": "Die Reise",
      "reise.hero_title": "DIE REISE",
      "reise.hero_subtitle": "TCM-Intensivausbildung & Daoistisches Retreat in China",
      "reise.hero_dates": "10. – 20. Oktober 2026 | 10 Tage, 10 Nächte",
      "reise.overview_title": "Teil 1: TCM-Intensivausbildung in Shenzhen",
      "reise.overview_desc": "In diesen fünf Tagen werden Meister Xu Ruqi und sein Team uns durch eine Balance aus TCM-Theorie und Praxis führen. Sie lernen die Prinzipien der TCM aus einer kulturellen, medizinischen und historischen spirituellen Perspektive kennen und beobachten gleichzeitig Live-Patientenbehandlungen in seinem neu eröffneten Krankenhaus im Herzen der Stadt.",
      "reise.wudang_title": "Teil 2: Integration in das heilige Landleben Chinas",
      "reise.wudang_desc": "Am 15. Oktober reisen wir in die Wudang-Berge, eine legendäre daoistische Landschaft. Wir wohnen in der ländlichen Privatresidenz des daoistischen Priesters Yin Chen Zi und seiner Frau Li Xin, teilen biologische, hausgemachte Mahlzeiten und das tägliche Leben in enger Verbundenheit mit dem Land.",
      "reise.itinerary_title": "Der Reiseablauf",
      "reise.day_arrival": "09. Oktober | Ankunftstag",
      "reise.day_arrival_desc": "Ankunft in Shenzhen & Check-in im Hotel Qianhai Gongyu. Einzelzimmer für jeden Teilnehmer. Gemeinsames Abendessen.",
      "reise.day_prep": "10. Oktober | Willkommen & Vorbereitung",
      "reise.day_prep_desc": "Orientierung & Gruppen-Einführung. Eröffnungsmeditation und Klangsession. Individuelle Pulsdiagnose durch Meister Xu für jeden Teilnehmer mit personalisierten Kräuterrezepturen.",
      "reise.day_tcm": "10. – 14. Oktober | TCM-Intensivtraining",
      "reise.day_tcm_desc": "4 Tage intensives Lernen & Üben. Kernthemen: Historische Einblicke, Puls- & Zungendiagnostik, Yin-Yang-Theorie sowie Live-Beobachtungen von Patientenbehandlungen.",
      "reise.day_wudang": "15. – 20. Oktober | Integration in den Wudang-Bergen",
      "reise.day_wudang_desc": "Reise nach Wudang. Leben an der ursprünglichen Quelle des Qi. Ausflüge zu kulturellen Stätten, daoistischen Tempeln, Teezeremonien und optionale Behandlungen (Moxa, Schröpfen, Gua Sha).",
      "reise.pricing_title": "Preise & Zahlungspläne",
      "reise.pricing_subtitle": "Wähle den passenden Plan für deine Reise",
      "reise.price_earlybird": "Frühbucher",
      "reise.price_earlybird_desc": "Gültig bis 31. Mai",
      "booking.popular": "Am beliebtesten",
      "reise.price_standard": "Standard-Preis",
      "reise.price_standard_desc": "Regulärer Buchungstarif",
      "reise.price_couple": "Paar-Angebot",
      "reise.price_couple_desc": "Für zwei Teilnehmer",
      "booking.contact_us": "Jetzt Kontakt aufnehmen",
      "reise.inclusions": "Inklusive: Unterkunft, Verpflegung, Unterricht, Inlandszug nach Wudang. <br>Exklusive: Internationale Flüge & Visum.",
      "nav-home": "Startseite",
      "nav-about": "Über uns & Meister",
      "nav-treatments": "Gesundheitspflege",
      "nav-devices": "Medizintechnik",
      "nav-programs": "Programme",
      "nav-retreat": "Retreat",
      "nav-info": "Klinik-Info",
      "nav-apply": "Anmelden",
      "hero-tag": "Traditionelle Chinesische Medizin trifft moderne Medizintechnik",
      "hero-title": "Traditionelle Chinesische Medizin &amp; Klinische Diagnostik",
      "hero-desc": "Erleben Sie tiefe körperliche und spirituelle Transformation durch die 40-jährige TCM-Erfahrung von Professor Xu Ruqi, individuelle Kräutertherapien, modernste Diagnosegeräte und heilsame Klangzeremonien.",
      "hero-cta-apply": "Jetzt anmelden",
      "hero-cta-more": "Programme entdecken",
      "intro-title": "Klassische Rezepturen als Fundament, Technologie als Flügel",
      "intro-desc": "<p style=\"margin-bottom: 1rem;\">Die Hong Dao Klinik wurde von einem Team renommierter Experten der SHANGHANLUN 伤寒论 Lehre des aufgestiegenen Meisters ZHANG Zhongjings 张仲景 sowie Doktoranden der Fudan University gegründet und verbindet klassische chinesische Kräuterrezepturen mit moderner Technologie und Diagnostikverfahren.</p><p style=\"margin-bottom: 1rem;\">Unter dem Leitgedanken „Klassische Rezepturen als Fundament, Technologie als Flügel“ vereint die Klinik Forschung und Lehre in einem integrativen Konzept und dient Menschen weltweit.</p><p>Wir bieten individuell maßgeschneiderte Begleitung und Therapiepläne für Patient:innen an, die unter komplexen Erkrankungen wie Autoimmungeschehen, Stoffwechselerkrankungen wie Diabetes, Endometriose, hormonellen Störungen, Erschöpfungssyndrom, Krebs und Unfruchtbarkeit leiden.</p>",
      "team-tag": "Unser Ärzteteam",
      "team-title": "Bewahrer des Wissens & Klinische Experten",
      "team-subtitle": "Lernen Sie unser engagiertes Team kennen, das Brücken zwischen Tradition und moderner Genesung schlägt.",
      "master-xu-title": "Chefarzt & TCM-Professor",
      "master-xu-desc": "Professor Xu Ruqi verfügt über mehr als 40 Jahre Erfahrung in Pulsdiagnostik und klassischer Kräutermedizin. Als klinischer Experte an der Pekinger Universität für Chinesische Medizin ist er weltweit bekannt für die Behandlung schwerer chronischer Krankheiten, Tumoren und gynäkologischer Leiden.",
      "doctor-1-title": "Direktorin der Klinik & Stammzelltherapie",
      "doctor-1-name": "Dr. Qiao Jingwen <span style=\"white-space: nowrap;\">(乔靖文)</span>",
      "doctor-1-desc": "Dr. Qiao Jingwen ist Direktorin der Hong Dao Klinik und kombiniert modernste Stammzelltherapie mit TCM-Rejuvenationstechniken für zelluläre Gesundheit, Fruchtbarkeit und hormonelle Balance.",
      "doctor-4-name": "Dr. Guan Weina (管蔚娜)",
      "doctor-4-spec": "Staatlich lizenzierte TCM-Ärztin. Spezialistin für Meridian-Entgiftung, Akupunktur und therapeutische Massagen.",
      "doctor-5-name": "Dr. Zhang Hailin (张海林)",
      "doctor-5-spec": "Leiterin des Dekokt-Zentrums. Expertin für traditionelle Kräuterzubereitung und Qualitätskontrolle.",
      "btn-read-bio": "Profil lesen",
      "decoction-subtitle": "Hauseigene Kräuter-Manufaktur",
      "decoction-title": "Modernes Dekokt-Zentrum & Dao Di Kräuter",
      "decoction-desc": "<p style=\"margin-bottom: 1.5rem;\">Wir beziehen ausschließlich hochwertige <strong>Dao Di Kräuter (道地藥材)</strong> aus kontrolliert biologischem Anbau und Soil-Technik aus den Herkunftsregionen, die für die jeweilige Pflanze die optimalen klimatischen und energetischen Bedingungen bieten.</p><p>In unserem hauseigenen Dekokt-Zentrum werden die Heilkräuter unter Aufsicht von Meister Xu individuell für Sie extrahiert, präzise verarbeitet und portioniert als <strong>gebrauchsfertige Kräuterdekokte (Ready-to-Drink)</strong> abgepackt, die Sie unkompliziert mit nach Hause nehmen können.</p>",
      "visionary-deng-title": "Heilpraktikerin, Qi Gong & Klangbegleitung",
      "visionary-deng-desc": "Heilpraktikerin Deng Nanjing übersetzt die Konsultationen und Befunde von Professor Xu verlässlich ins Deutsche, Englische, Italienische, Spanische und Mandarin. Begleitend leitet sie Qi Gong, die 6 heilenden Klänge, Klangsitzungen und Teezeremonien und unterstützt Sie bei allen organisatorischen Anliegen während Ihres Aufenthaltes.",
      "visionary-deng-spec": "Heilpraktikerin, Qi Gong, Klangbegleitung & Patientenbetreuung. 5 Sprachen.",
      "team-grid-title": "Unser spezialisiertes Team",
      "doctor-3-name": "Dr. Chen Kainan (陈恺楠) — Assistenzarzt",
      "doctor-3-spec": "Assistenzarzt, spezialisiert auf Akupunktur und klinische Unterstützung unter Anleitung von Professor Xu.",
      "doctor-sound-name": "Cheung Mingli (张明丽)",
      "doctor-sound-spec": "Gründerin von Voice Alchemy, internationale Klangheilerin & Begleiterin für Stimmaktivierung mit über 10 Jahren Erfahrung.",
      "treatments-title": "Fachbereiche der Gesundheitspflege",
      "treatments-subtitle": "Maßgeschneiderte Begleitung für Ihre gezielte Regeneration.",
      "treatment-1-title": "Endometriose & Frauengesundheit",
      "treatment-1-desc": "Individuelle Kräuterpasten, Womb-Massage (Gebärmutter-Massage) und Akupressur zur Lösung von Stagnationen und Schmerzlinderung.",
      "treatment-2-title": "Stammzellen & Langlebigkeit",
      "treatment-2-desc": "Dr. Adrianna Qiao kombiniert modernste Stammzelltherapie mit TCM-Rejuvenationstechniken für zelluläre Erneuerung.",
      "treatment-3-title": "Stress & Burnout-Prävention",
      "treatment-3-desc": "Ganzheitliche Begleitung bei Belastungszuständen durch pulsgeführte Akupunktur und begleitende Klangtherapie.",
      "devices-title": "Technologie zur Gesundheitspflege",
      "devices-subtitle": "Traditionelle TCM-Diagnostik, präzisiert durch modernste klinische Geräte.",
      "device-1-name": "Infrarot-Körperscan",
      "device-1-desc": "Visualisiert Entzündungen, Durchblutungsverstörungen und energetische Meridianblockaden mittels HD-Thermografie.",
      "device-1-uses": "Primäre Anwendung: Lenden- und Halswirbelsäule, Durchblutung, Entzündungsscreening, Stoffwechsel.",
      "device-2-name": "Bian-Hu Bioelektrizitäts-Therapie",
      "device-2-desc": "Verbindet erwärmten Bian-Stein-Massage-Kopf mit bioelektrischer Mittelfrequenz-Regulation.",
      "device-2-uses": "Primäre Anwendung: Schulterschmerzen, HWS-Syndrom, Bandscheibenvorfall, Magen-Darm-Störungen, Endometriose (PCOS/PMOS).",
      "device-3-name": "Kräuter-Wärme-Moxibustion",
      "device-3-desc": "Patentiertes, raucharmes Großflächen-Wärme-Moxibustion-System (Pu Jiu) für Wirbelsäule und Gelenke.",
      "device-3-uses": "Primäre Anwendung: Regelschmerzen & kalte Gebärmutter, Lenden- & Knieschmerz, Unterleibsentzündungen, Wirbelsäule.",
      "device-4-name": "Thermo-Stoffwechselkabine",
      "device-4-desc": "Ganzkörper-Spektralkabine mit Farbinfrarot, Sauerstoffanreicherung und negativen Ionen zur Zellreinigung.",
      "device-4-uses": "Primäre Anwendung: Sportliche Regeneration, Fortpflanzungsgesundheit, chronische Leiden, metabolische Entgiftung.",
      "device-5-name": "Mikro-Photonen-Moxibustion",
      "device-5-desc": "Lokalisiertes Spektral-Bestrahlungsgerät (560-1400 nm) zur tiefenwirksamen Entzündungshemmung (7-10 cm).",
      "device-5-uses": "Primäre Anwendung: Entzündungen & Schmerz, Gelenkschmerz, Hautregeneration, kosmetische Zwecke, Arthritis, Sportverletzungen.",
      "endo-details-link": "Details ansehen",
      "programs-title": "Gesundheitsprogramme & Kurse",
      "programs-subtitle": "Vom intensiven Ausbildungskurs bis zum maßgeschneiderten Gesundheitspflege-Programm.",
      "retreat-10day-title": "10-tägiges TCM-Training & Retreat",
      "retreat-10day-date": "10. Oktober - 20. Oktober 2026",
      "retreat-10day-desc": "Komplette Immersion in TCM-Theorie & Praxis. 5 Tage klinische Hospitation in Shenzhen unter Meister Xu, gefolgt von 5 Tagen taoistischer Lebensführung in den Wudang-Bergen. Ein 3-monatiger Online-Vorbereitungskurs ist inklusive! Maximal 12 Teilnehmer.",
      "retreat-10day-price": "€3.900,- Kostenbeitrag (Frühbucher)",
      "retreat-10day-wix-link": "Details ansehen",
      "retreat-1day-title": "1- bis 5-tägiges klinisches TCM-Training (Shenzhen)",
      "retreat-1day-desc": "Lokale Tageskurse vor Ort. Ideal für Therapeuten und Interessierte zur Hospitation, Pulsdiagnose-Einführung und Kräuterküchen-Zubereitung.",
      "retreat-1day-price": "€250,- Kostenbeitrag pro Tag",
      "endo-program-title": "Endometriose-Gesundheitspflegeprogramm",
      "endo-program-desc": "Ein spezialisiertes, individuell anpassbares Gesundheitspflege-Programm für Frauen. Enthält Kräuterrezepturen, Womb-Massagen, Sound Healing, Ernährungsanalyse und Begleitung.",
      "endo-select-duration": "Programmdauer wählen:",
      "endo-btn-book": "Direkt buchen & bezahlen (Stripe)",
      "endo-btn-inquire": "Jetzt bewerben / Anfragen",
      "duration-1w": "1 Woche",
      "duration-2w": "2 Wochen",
      "duration-4w": "4 Wochen",
      "endo-price": "Kostenbeitrag auf Anfrage",
      "package-basic": "Ambulant (ohne Unterkunft)",
      "package-premium": "Premium (inkl. Partnerhotel & TCM-Küche)",
      "endo-included-title": "Inklusive Leistungen:",
      "endo-price-note": "*Hinweis: Die Kostenbeiträge beinhalten keine individuelle Kräutermedizin.",
      "yunnan-title": "Berg-Retreats & Natur-Verlängerung",
      "yunnan-subtitle": "Ein heilsamer Übergang von der Stadtklinik in die unberührte Natur.",
      "yunnan-desc-1": "Erweitern Sie Ihr klinisches Programm mit einem Natur-Retreat. Jedes Behandlungsprogramm, jede Ausbildung und jedes Retreat beginnt mit intensiver Diagnose und Therapie in der Shenzhen-Klinik, bevor Sie direkt zu Chinas unberührten Bergheiligtümern reisen.",
      "yunnan-desc-2": "Der zweite und vertiefende Teil findet immer an einem wunderschönen Ort in den Bergen Chinas statt. Wir nutzen ein traditionelles Gästehaus, betrieben vom taoistischen Meister Yin Chen Zi und seiner Frau in den Wudang-Bergen, sowie Unterkünfte in Wuyi Shan und Yunnan (Xishuangbanna).",
      "yunnan-hotel-info": "Unterkünfte beinhalten: Traditionelles Gästehaus aus Holz in Wudang (Meister Yin Chen Zi), malerische Herbergen in Wuyi Shan sowie das luxuriöse Yunnan Horizon Sanctuary Öko-Resort.",
      "yunnan-meta-title": "Hong Dao TCM Clinic | Yunnan Tee-, Pilz- und Kräuter-Kulturreise",
      "yunnan-meta-desc": "Intensive Natur-, Heil- und Kulturerfahrung in den Bergen Yunnans. Entdecken Sie alte Teewälder, Heilpilze, TCM und das Leben der Minderheitenvölker.",
      "yunnan-page-hero-tag": "6-tägige Yunnan Kulturreise & Retreat",
      "yunnan-page-hero-title": "YUNNAN RETREAT",
      "yunnan-page-hero-subtitle": "6-tägige Tee-, Pilz- und Kräuter-Kulturreise mit den Minderheitenvölkern",
      "yunnan-page-header": "Das Erwecken der Lebenskraft",
      "yunnan-page-subheader": "Eine transformative Reise in die unberührte Natur Chinas",
      "yunnan-page-intro": "Diese Reise ist eine intensive Natur-, Heil- und Kulturerfahrung in den Bergen Yunnans. Sie verbindet die Weisheit des Daoismus, Traditionelle Chinesische Medizin (TCM), Heilpilze, alte Teekulturen und das Leben der Hani-Minderheit und anderer Bergvölker zu einer tiefen Regenerations- und Selbsterfahrungsreise.",
      "yunnan-page-core-idea-title": "Die Grundidee",
      "yunnan-page-core-idea-desc": "Im Zentrum steht die Wiedererweckung der „Lebenskraft“ (生命原力) – jener natürlichen Energie, die laut daoistischer und chinesischer Medizin Gesundheit, Kreativität, Vitalität und innere Klarheit nährt.",
      "yunnan-page-transform-title": "Der dreistufige Transformationsprozess:",
      "yunnan-page-transform-1": "<strong>1. Jing (Essenz) – Fundament schaffen:</strong> Körperliche Regeneration, Aufbau von Energie und Ressourcen, Ernährung, Heilkräuter und Heilpilze.",
      "yunnan-page-transform-2": "<strong>2. Qi (Lebensenergie) – Aktivieren und Verwandeln:</strong> Atemarbeit, Daoistische Übungen, Bewegung und Energiearbeit, Öffnung und Harmonisierung der Meridiane.",
      "yunnan-page-transform-3": "<strong>3. Shen (Geist) – Verfeinerung und Bewusstsein:</strong> Meditation, Klangheilung, Innere Klarheit und emotionale Balance, Verbindung mit dem eigenen Wesenskern.",
      "yunnan-page-experts-title": "Begleitung durch Experten",
      "yunnan-page-experts-desc": "Während der gesamten Reise begleiten die Gruppe:",
      "yunnan-page-expert-1": "Ein renommierter TCM-Meister für Puls- und Zungendiagnose",
      "yunnan-page-expert-2": "Ein TCM-Arzt und Gesundheitscoach",
      "yunnan-page-expert-3": "Ein international zertifizierter Klangtherapeut",
      "yunnan-page-expert-4": "Lokale Pilzexperten der Hani-Minderheit",
      "yunnan-page-expert-5": "Teebauern und Kräuterkundige aus den Bergen Yunnans",
      "yunnan-page-experts-note": "Jeder Teilnehmer erhält eine individuelle TCM-Diagnose mit persönlichen Empfehlungen zu Kräutern, Ernährung und Lebensstil.",
      "yunnan-page-experience-title": "Was die Teilnehmer erleben",
      "yunnan-page-exp-nervous-title": "Ankommen & Nervensystem regulieren",
      "yunnan-page-exp-nervous-desc": "Die Reise beginnt mit einer feierlichen Eröffnungszeremonie, Atemarbeit, Klangheilung, gemeinsamer Resonanzarbeit, einer Blauen-Lotus-Teezeremonie und Intention Setting. Ziel ist es, das Nervensystem aus dem Stressmodus in den Regenerationsmodus zu bringen.",
      "yunnan-page-exp-forest-title": "Alte Teewälder & Heilpilze entdecken",
      "yunnan-page-exp-forest-desc": "Ein Höhepunkt ist die Wanderung durch die uralten Teewälder des Nan Nuo Shan, einem der ältesten Pu-Erh-Tee-Gebiete Yunnans. Dort erleben die Teilnehmer bis zu 800 Jahre alte Teebäume, wild wachsende Heilkräuter, traditionelle Kräuterkunde und Heilpilzsuche mit Hani-Guides. Gesammelt und erklärt werden unter anderem: <strong>Reishi (Lingzhi), Poria (Fu Ling), Roter Heilpilz (Da Hong Jun), Puffball-Pilze (Ma Bo), Dendrobium, Polygonatum, Angelika-Wurzel</strong> und weitere Bergkräuter. Die Teilnehmer lernen nicht nur ihre Wirkung kennen, sondern legen eigene Heilpilz- und Kräuterkarten an.",
      "yunnan-page-exp-ethnicity-title": "Leben mit den Ethnien Yunnans",
      "yunnan-page-exp-ethnicity-desc": "Ein besonderer Aspekt der Reise ist der direkte Konakt mit den lokalen Ethnien Yunnans. Die Teilnehmer erfahren traditionelle Pilzsammlung, Teeherstellung, lokale Heilmethoden, traditionelle Ernährung und die spirituelle Naturverbundenheit der Bergvölker. Dadurch entsteht ein authentischer Einblick in eine Lebensweise, die seit Jahrhunderten eng mit Wald, Bergen und den Jahreszeiten verbunden ist.",
      "yunnan-page-exp-daoist-title": "Daoistische Praxis & Lebenspflege",
      "yunnan-page-exp-daoist-desc": "Täglich finden Qi Gong, daoistische Atemtechniken, Meditation, Körperwahrnehmungsübungen, Energiearbeit und Übungen zur Hormon- und Emotionsregulation statt. Diese Praktiken sollen Stress reduzieren, den Vagusnerv aktivieren, die Schlafqualität verbessern, das Hormonsystem harmonisieren und die Selbstheilungskräfte stärken.",
      "yunnan-page-exp-sound-title": "Klangheilung & innere Transformation",
      "yunnan-page-exp-sound-desc": "Ein weiterer Schwerpunkt sind tiefe Klang- und Frequenzreisen: Stimmarbeit, Mantra-Meditation, Heilfrequenzen, Trance- und Hypnoseelemente sowie „Tree of Life“-Klangreisen. Die Arbeit mit Klang soll Herzrhythmus, Atem- und Gehirnwellen synchronisieren und tiefe Entspannung ermöglichen.",
      "yunnan-page-target-title": "Für wen die Reise gedacht ist",
      "yunnan-page-target-desc": "Ideal für Menschen, die unter chronischem Stress stehen, Erschöpfung oder Burnout vorbeugen möchten, ihre Gesundheit ganzheitlich stärken wollen, sich für TCM, Heilpilze und Teekultur interessieren, eine tiefere Verbindung zur Natur suchen oder daoistische Lebenskunst erleben möchten.",
      "yunnan-page-essence-title": "Essenz der Reise",
      "yunnan-page-essence-desc": "Diese Reise ist weit mehr als ein Retreat. Sie ist eine Begegnung mit den uralten Teewäldern Yunnans, den Heilpilzen des Bergwaldes, dem Wissen der Minderheitenvölker und den daoistischen Wegen zur Kultivierung von Körper, Energie und Geist. Man lernt nicht nur über Tee, Pilze und Kräuter – man erlebt unmittelbar, wie Natur, traditionelle Heilkunst und innere Praxis zusammenwirken können, um Vitalität, Ruhe und Lebensfreude neu zu entdecken.",
      "child-title": "Hong Dao Kinderbereich",
      "child-desc": "Heilung betrifft die ganze Familie. Unsere Klinik bietet einen hauseigenen Kinderbereich (Child Space) mit kindgerechten Beschäftigungen, TCM-Ernährungsberatung und regelmäßigen öffentlichen & internen Events.",
      "info-title": "Klinikinformationen & Buchungsrichtlinien",
      "info-location-label": "Standort & Anfahrt",
      "info-location-desc": "Hong Dao TCM-Klinik, Nanshan District, Shenzhen. Gut angebunden an Metro und Autobahn.",
      "info-hours-label": "Öffnungszeiten",
      "info-hours-desc": "Montag - Samstag: 09:00 - 18:00 Uhr (Nur nach Terminvereinbarung)",
      "info-payment-label": "Anmeldung & Kostenbeitrag",
      "info-payment-desc": "Die Online-Anmeldung ist möglich. Die Anmeldung gilt erst nach Erhalt der Bestätigungs-E-Mail als offiziell bestätigt. Alle Kostenbeiträge fließen direkt in die Deckung der Aufwände für die Gesundheitspflege-Programme der Klinik.",
      "faq-title": "Häufig gestellte Fragen (FAQ)",
      "faq-q1": "Sind die verschriebenen Kräuter im Kostenbeitrag inbegriffen?",
      "faq-a1": "Nein. Individuell verschriebene Kräuterarzneien (die als Pulver oder Paste mit nach Hause genommen werden können) werden je nach individuellem Aufwand und Bedarf separat bereitgestellt.",
      "faq-q2": "Wie läuft der Transfer nach Yunnan ab?",
      "faq-a2": "Unser Klinikteam organisiert den Transfer per Bahn/Flug. Unterkunft im Partnerhotel sowie Aktivitäten vor Ort sind im Kostenbeitrag des Retreats enthalten.",
      "faq-q3": "Gibt es eine Kinderbetreuung vor Ort?",
      "faq-a3": "Ja. Unser hauseigener Kinderbereich bietet altersgerechte Programme und veranstaltet regelmäßige Familien-Events.",
      "faq-q4": "Brauche ich ein Visum für China?",
      "faq-a4": "Die meisten EU-Bürger (inkl. Deutschland, Österreich, Schweiz) können seit 2024 visumfrei für bis zu 30 Tage nach China einreisen. Bitte prüfen Sie die aktuellen Einreisebestimmungen Ihres Landes vor Abreise.",
      "faq-q5": "Welche Apps brauche ich in China?",
      "faq-a5": "<strong>Vor Abreise installieren:</strong><br>&#8226; <strong>WeChat</strong> &#8211; Kommunikation (Chinas WhatsApp)<br>&#8226; <strong>Alipay</strong> &#8211; Bezahlen (Kreditkarte verknüpfen!)<br>&#8226; <strong>Didi</strong> &#8211; Taxi bestellen<br>&#8226; <strong>AMap</strong> &#8211; Navigation<br>&#8226; <strong>VPN</strong> &#8211; z.B. Jamjams oder Potatso Lite",
      "faq-q6": "Wie funktioniert das Bezahlen vor Ort?",
      "faq-a6": "In China wird fast ausschließlich bargeldlos bezahlt. Laden Sie <strong>Alipay</strong> herunter und verknüpfen Sie Ihre Kreditkarte (Visa/Mastercard). Damit können Sie überall bezahlen.",
      "faq-q7": "Was kann ich von einer TCM-Behandlung erwarten?",
      "faq-a7": "Professor Xu erstellt eine individuelle Diagnose über Pulsdiagnostik und Zungenanalyse. Die Behandlung umfasst Kräuterrezepturen, Akupunktur und Moxibustion. Erste Verbesserungen zeigen sich oft nach 1-2 Wochen, nachhaltige Veränderungen nach 4+ Wochen.",
      "contact-tab-calendly": "📅 Termin online buchen",
      "contact-tab-form": "✉️ Bewerbungsformular",
      "contact-title": "Beginnen Sie Ihren Weg zur Heilung",
      "contact-subtitle": "Kontaktieren Sie uns oder bewerben Sie sich direkt für Ihr individuelles Heilprogramm.",
      "contact-free-consult": "Kostenloses 15-minütiges Gespräch anfragen",
      "contact-free-desc": "Sprechen Sie direkt mit Nanjing Deng, um Ihre Beschwerden zu besprechen und das passende Programm zu finden.",
      "contact-label-name": "Name",
      "contact-label-email": "E-Mail-Adresse",
      "contact-label-phone": "Telefonnummer",
      "contact-label-program": "Gewünschtes Programm",
      "contact-label-date": "Datum des Beratungsgesprächs (Mittwoch / Samstag)",
      "contact-label-slot": "Uhrzeit wählen (Pekinger Ortszeit 14:00 - 20:00 Uhr)",
      "contact-label-message": "Kurze Anmerkung zu Ihren Beschwerden",
      "contact-submit-btn": "Jetzt anmelden",
      "contact-submit-email": "Per E-Mail anmelden",
      "contact-submit-whatsapp": "Per WhatsApp anmelden",
      "contact-social-text": "Folgen Sie uns in den sozialen Medien für Gesundheitstipps, Klangzirkel und Tee-Rituale:",
      "whatsapp-text": "Über WhatsApp chatten",
      "instagram-text": "Instagram: nanjing_tea.sound",
      "booking-success-toast": "Registrierung erfolgreich gesendet! Eine Bestätigung wird an Ihre E-Mail gesendet.",
      "card-select-start-date": "Starttermin wählen:",
      "contact-label-start-date": "Gewünschter Starttermin des Programms",
      "popup-title": "Willkommensangebot",
      "popup-desc": "Registrieren Sie sich heute für die Endometriose-Programme oder das Wudang-Retreat und erhalten Sie 10% Ermäßigung auf den Kostenbeitrag der Erstkonsultation.",
      "popup-code-label": "Ihr Registrierungscode:",
      "popup-cta": "Mit Code registrieren",
      "treatment-4-badge": "Pilzheilkunde",
      "treatment-4-title": "Pilzheilkunde & Myzel-Regulation",
      "treatment-4-desc": "Lösung von Blockaden in den Membranen (膜络) durch medizinale Großpilze (Poria, Reishi, Cordyceps) zur sanften Schrumpfung von Gewebeknoten und Regulation des Nervensystems.",
      "nav-resources": "Handbücher",
      "resources-tag": "Wissenschaft & Downloads",
      "resources-title": "Klinik-Handbücher & Forschung",
      "resources-subtitle": "Laden Sie offizielle Handbücher unserer Medizintechnik herunter und vertiefen Sie Ihr Wissen über unsere Behandlungssysteme.",
      "wisdom-tag": "WeChat-Wissenschaft & Klinische Praxis",
      "wisdom-title": "Die Weisheit der Pilzmedizin: Vom Erdboden zu den Membranen",
      "wisdom-text": "<p style=\"margin-bottom: 1rem;\">Unter der Erde erstreckt sich ein neuronales Netzwerk – das „Wood Wide Web“. Genau wie dieses planetare Immunsystem arbeiten Pilze in unserem Körper durch Symbiose und Regulation. Sie verbinden sich mit unseren „膜络“ (membranösen Kollateralen), um Blockaden zu lösen, Feuchtigkeit zu transformieren und Knoten (Zysten, Myome, Schilddrüsenknoten) aufzulösen.</p><p>In unserer klinischen Praxis verbinden wir diese Naturgesetze mit moderner Begleitung. Lesen Sie die vollständige wissenschaftliche Ausarbeitung von Dr. Zhang Hailing und Dr. Chen Kainan.</p>",
      "wisdom-link": "Original-Artikel lesen (WeChat)",
      "cases-title": "Klinische Fallstudien",
      "case-1": "<strong>Fall 1 (Schilddrüsenknoten, 2.1cm):</strong> Vollständige Symptomlinderung und Knotenschrumpfung auf 0.9cm nach 3 Monaten Therapie mit Poria & Reishi.",
      "case-2": "<strong>Fall 2 (Brustdrüsen-Hyperplasie & Angst):</strong> Auflösung von Brustknoten (1.6cm) und Linderung von Herzklopfen/Schlaflosigkeit durch Myzel-Regulation.",
      "download-program-brochure": "Retreat-Programmbuch herunterladen (PDF)",
      "manuals-grid-title": "Medizinische Geräte-Handbücher & Broschüren",
      "pdf-1-title": "Spektrum-Therapiegerät 2.0",
      "pdf-1-desc": "Detailliertes Handbuch zur thermischen Spektrallicht-Therapie zur Entgiftung und Meridianstärkung.",
      "pdf-2-title": "Pian-Stein Mittelfrequenz-Therapie",
      "pdf-2-desc": "Bedienungsanleitung und Anwendungsbereiche des warmen Pian-Stein-Behälters zur Meridian-Massage.",
      "pdf-3-title": "Infrarot-Thermografie 4.0",
      "pdf-3-desc": "Broschüre zur thermischen Bildgebung und Diagnostik von Durchblutung und Entzündungsherden.",
      "pdf-4-title": "铺灸 / Pu Jiu Handbuch 3.1",
      "pdf-4-desc": "Klinische Richtlinien zur Rücken-Moxibustion zur Beseitigung tiefer Kälte und Stärkung des Yang.",
      "pdf-5-title": "Frequenz-Hyperthermie-Kabine 3.5",
      "pdf-5-desc": "Bedienung und therapeutischer Nutzen der Ganzkörper-Wärmekabine zur Entgiftung und Immun-Aktivierung.",
      "pdf-6-title": "Dao-Pilz-Retreat Programm",
      "pdf-6-desc": "Exklusive Broschüre zum Retreat „Awakening and Transforming the Life Force“ in den Wudang-Bergen.",
      "pdf-download-btn": "PDF herunterladen",
      "treatment-1-badge": "Gynäkologie",
      "treatment-2-badge": "Zelltherapie",
      "treatment-3-badge": "Neurologie",
      "nav-tech-btn": "TCM-Technologie",
      "tech-modal-title": "Klinische Medizintechnik & Therapieverfahren",
      "tech-download-manual": "Handbuch herunterladen (PDF)",
      "tech-device-2-title": "Bian-Stein Mittelfrequenz-Elektrotherapie",
      "tech-device-2-long-desc": "Verbindet Akupressur-Punkte mit gezielten Frequenzen zur Anregung des Zellstoffwechsels und zur Entlastung des Muskel-Skelett-Systems. Stimuliert blockierte Leitbahnen (Meridiane) mittels biologischer Frequenzen.",
      "tech-device-3-title": "Großflächen-Moxibustion (铺灸 - Pu Jiu)",
      "tech-device-3-long-desc": "Eine Wärmetherapie auf großen Körperflächen (wie dem Rücken), bei der Beifußkraut gezielt verbrannt wird, um Kälte aus den Leitbahnen zu vertreiben, die Yang-Energie zu stärken und das Immunsystem zu regulieren.",
      "tech-device-4-title": "Ganzkörper-Spektralkabine",
      "tech-device-4-long-desc": "Nutzt ein breites elektromagnetisches Frequenzspektrum zur Erwärmung des Gewebes. Fördert die periphere Mikrozirkulation, unterstützt die zelluläre Ausleitung und lindert chronische Muskelverspannungen.",
      "tech-device-5-title": "Lokalisiertes Spektral-Bestrahlungsgerät",
      "tech-device-5-long-desc": "Gezielter Spektralstrahler zur lokalen Bestrahlung. Fördert die Geweberegeneration, regt lokale Stoffwechselprozesse an und wird komplementär zu Akupunktur- und Moxa-Sitzungen eingesetzt.",
      "read-details-btn": "Details lesen",
      "gallery-title": "Impressionen aus unserem letzten Retreat 2025",
      "gallery-more-btn": "Mehr Bilder",
      "gallery-subtitle": "Bilder und Momente des gemeinsamen Trainings, der Meditationen und Naturerfahrungen.",
      "gallery-item-group-badge": "Gruppe",
      "gallery-item-group-title": "Retreatgruppe 2025",
      "gallery-item-meditation-badge": "Meditation",
      "gallery-item-meditation-title": "Klangmeditation",
      "gallery-item-qigong-badge": "Qi Gong",
      "gallery-item-qigong-title": "Morgen Qi Gong",
      "gallery-item-tea-badge": "Zeremonie",
      "gallery-item-tea-title": "Tee-Zeremonie",
      "gallery-item-lecture-badge": "Theorie",
      "gallery-item-lecture-title": "Pulsdiagnose",
      "gallery-item-nature-badge": "Natur",
      "gallery-item-nature-title": "Wandern & Kräuter",
      "gallery-item-practice-badge": "Praxis",
      "gallery-item-practice-title": "Moxa-Training",
      "gallery-item-kitchen-badge": "Ernährung",
      "gallery-item-kitchen-title": "Heilküche",
      "gallery-item-soundbath-badge": "Klangbad",
      "gallery-item-soundbath-title": "Klangbad in Natur",
      "btn-read-article": "Artikel lesen",
      "btn-read-details": "Details ansehen",
      "endo-read-approach": "Behandlungsansatz & Fallbeispiele",
      "footer-impressum": "Impressum",
      "footer-privacy": "Datenschutz",
      "contact-wechat-wrapper": "<strong>WeChat:</strong> <a href=\"#\" class=\"read-article-btn\" data-article=\"wechat\" style=\"color: var(--terracotta); text-decoration: underline; font-weight: 500;\">QR-Codes anzeigen</a>",
      "endo-meta-title": "Hong Dao TCM Clinic | Endometriose Programm",
      "endo-page-hero-tag": "Endometriose Programm",
      "endo-page-title": "Eine Reise zurück zu deinem Ursprung",
      "endo-page-subtitle": "Ganzheitliche Begleitung für Frauen mit Endometriose in China",
      "endo-page-header": "Dein Körper kämpft nicht gegen dich.<br><span style=\"font-size: 1.5rem; color: var(--text-dark);\">Vielleicht ist es an der Zeit, aufzuhören gegen ihn zu kämpfen.</span>",
      "endo-page-intro": "<p>Komm mit uns nach China.</p><p>Zu den Wurzeln einer Medizin, die seit Jahrtausenden die Sprache des weiblichen Körpers versteht.</p><p>Zu den Nebelbergen Yunnans.</p><p>Zu Ruhe, Akzeptanz, Gemeinschaft als Frauen und neuer Hoffnung.</p><p>Und vielleicht ein Stück näher zu deiner weiblichen Essenz</p>",
      "endo-page-body-1": "<p>Vielleicht hast du bereits einen langen Weg hinter dir.</p><p>Vielleicht wurden deine Schmerzen mit Hormonen unterdrückt, vielleicht hast du bereits Operationen hinter dir oder dir wurde gesagt, dass weitere Eingriffe unvermeidbar sind. Viele Frauen mit Endometriose leben jahrelang zwischen Symptombehandlung, Unsicherheit und dem Gefühl, dass ihr Körper gegen sie arbeitet.</p><p><strong>Doch was wäre, wenn dein Körper nicht dein Gegner ist?</strong></p><p>Was wäre, wenn die Schmerzen, Erschöpfung, Entzündungen und Zyklusbeschwerden eine Sprache sprechen, die verstanden werden möchte?</p><p>In der Traditionellen Chinesischen Medizin betrachten wir Endometriose nicht als isolierte Erkrankung, sondern als Ausdruck eines tieferen Ungleichgewichts. Statt Symptome zu unterdrücken, fragen wir: Warum ist der Körper aus seiner Balance geraten? Was möchte er uns mitteilen? Und wie können wir ihn dabei unterstützen, zu seiner natürlichen Ordnung zurückzufinden?</p>",
      "endo-page-quote": "<p style=\"margin-bottom: 1rem;\">In einer Zeit, in der immer mehr Frauen nach natürlichen und ganzheitlichen Wegen suchen, öffnet uns China die Tür zu einem jahrtausendealten Wissen, das den weiblichen Körper nicht als Problem/Objekt betrachtet, sondern als intelligentes System, das nach Balance strebt.</p><p style=\"font-weight: 600;\">Wo die moderne Medizin oft fragt: „Was müssen wir entfernen?“, fragt die Chinesische Medizin: „Was müssen wir nähren, damit der Körper wieder in seine natürliche Ordnung findet?“</p>",
      "endo-week1-title": "Woche 1: Die Klinik in Shenzhen",
      "endo-week1-desc": "<p>Unsere Reise beginnt in Shenzhen, wo wir die erste Woche in einer erfahrenen TCM-Klinik verbringen. Durch eine umfassende Diagnostik erstellen wir einen individuellen Therapieplan, der auf deine persönliche Geschichte, deine Beschwerden und deine Konstitution abgestimmt ist.</p><p>Wir betrachten nicht nur die körperlichen Symptome, sondern auch Ernährung, Lebensstil, Stress, emotionale Belastungen und die tieferen Muster, die zu der Erkrankung beigetragen haben könnten. Gemeinsam entwickeln wir einen nachhaltigen Weg, der dich auch nach der Reise weiter begleiten kann.</p><p>Bereits in dieser ersten Woche beginnen wir mit deiner individuellen Kräutertherapie. Ergänzend nutzen wir moderne biomedizinische Verfahren wie die BianHu Bio-Medizinische Resonanz-Massage sowie weitere unterstützende Technologien, die dabei helfen können, Durchblutung, Gewebeversorgung und die natürlichen Regulationsprozesse des Körpers anzuregen.</p>",
      "endo-page-poetic": "<p>Die Chinesische Medizin spricht von / Meer des Blutes, von 衝脈 (Chōng Mài) – dem Meer der Weiblichkeit und Fruchtbarkeit, von 子宮 (Zǐ Gōng) – dem Palast des Kindes. Allein die Sprache zeigt eine tief verwurzelte Ehrfurcht vor dem weiblichen Körper.</p><div class=\"endo-poetic-highlight\"><p>Die Gebärmutter ist kein Organ, das bekämpft werden muss.<br><strong>Sie ist ein Palast.</strong></p><p style=\"margin-top: 1rem;\">Der Zyklus ist kein Problem.<br><strong>Er ist ein Rhythmus.</strong></p><p style=\"margin-top: 1rem;\">Die Menstruation ist kein lästiger Nebeneffekt.<br><strong>Sie ist eine Botschaft.</strong></p></div>",
      "endo-week2-title": "Woche 2: Tiefe Transformation in Yunnan",
      "endo-week2-desc-1": "<p>Nach der ersten Woche reisen wir gemeinsam in die magische Natur Yunnans. Umgeben von den Nebelbergen, uralten Wäldern und der Ruhe des ländlichen Chinas verbringen wir unsere Zeit in einem wunderschönen 5-Sterne-Hotel, fernab vom Lärm und der Hektik des Alltags.</p><p>Hier beginnt die tiefere Heilungsreise.</p><p>In China erleben wir nicht nur die Medizin, sondern auch die Weisheit einer Kultur, die sich zunehmend wieder auf ihre traditionellen Wurzeln besinnt. Zurück zur Natur. Zurück zu den Zyklen. Zurück zur Verbindung zwischen Mensch und Erde.</p>",
      "endo-week2-poetic": "Diese zweite Phase der Reise ist dem Yin gewidmet.<br>Dem Nähren.<br>Dem Empfangen.<br>Dem Loslassen.<br>Dem Erinnern.",
      "endo-week2-desc-2": "<p>Viele Frauen mit Endometriose haben über Jahre gelernt zu kämpfen, durchzuhalten und zu funktionieren. Hier darfst du erfahren, wie es sich anfühlt, nicht mehr gegen deinen Körper zu arbeiten, sondern mit ihm.</p><p>Durch ausreichend Schlaf, tiefgehende Entspannung, nährendes Essen, sanfte Bewegung, Qi Gong, Atemarbeit, Meditation und viel Zeit in der Natur schaffen wir die Bedingungen, in denen Regeneration überhaupt erst möglich wird.</p><p>Wir lernen wieder, was es bedeutet, als Frau mit den natürlichen Rhythmen des Lebens zu leben – mit Ebbe und Flut, Aktivität und Ruhe, Yang und Yin.</p><p>Während der gesamten Reise begleiten wir die Kräutertherapie weiter und beobachten gemeinsam die Veränderungen auf körperlicher, emotionaler und energetischer Ebene. Du wirst von einem erfahrenen Team getragen und unterstützt.</p>",
      "endo-page-cta-text": "Diese Reise ist kein Versprechen auf Heilung.<br>Sie ist eine Einladung.<br>Eine Einladung, einen anderen Weg kennenzulernen.<br>Einen Weg, der nicht auf Unterdrückung basiert, sondern auf Verständnis.<br>Nicht auf Kampf, sondern auf Kooperation.<br>Nicht auf Trennung, sondern auf Rückverbindung.<br><br>Eine Reise zurück zu deinem Körper.<br>Zurück zu deiner Weiblichkeit.<br>Zurück zu deinem Ursprung.",
      "endo-page-cta-btn": "Beratungsgespräch vereinbaren"
    }
  },
  "images": {
    "endo-card-img": "images/whatsapp_imports/wa_1781171825958_67ott.jpeg",
    "tcm-training-card-img": "images/whatsapp_imports/wa_1781172376651_1h73y.jpeg",
    "wellness-tour-card-img": "images/whatsapp_imports/wa_1781172001701_hkvkg.jpeg",
    "tcm-training-overview-img": "images/whatsapp_imports/wa_1781172376651_1h73y.jpeg",
    "yunnan-intro-img": "images/wuyishan_landscape.png",
    "wudang-guesthouse-img": "images/wudang_guesthouse.jpg",
    "yunnan-gallery-img-1": "images/yunnan_hotel1.png",
    "yunnan-gallery-img-2": "images/yunnan_hotel2.png",
    "yunnan-gallery-img-3": "images/yunnan_hotel3.png",
    "yunnan-gallery-img-4": "images/yunnan_hotel4.png",
    "yunnan-gallery-img-5": "images/whatsapp_imports/wa_1781335383_nmvej.jpeg",
    "yunnan-gallery-img-6": "images/whatsapp_imports/wa_1781335384_f7558.jpeg",
    "yunnan-gallery-img-7": "images/whatsapp_imports/wa_1781335384_s1k8k.jpeg",
    "yunnan-gallery-img-8": "images/whatsapp_imports/wa_1781335384_z24u4.jpeg",
    "yunnan-gallery-img-9": "images/whatsapp_imports/wa_1781335385_0m902.jpeg",
    "yunnan-gallery-img-10": "images/whatsapp_imports/wa_1781335385_4y3p1.jpeg",
    "yunnan-gallery-img-11": "images/whatsapp_imports/wa_1781335385_jfnx0.jpeg",
    "yunnan-gallery-img-12": "images/whatsapp_imports/wa_1781335386_dqwv9.jpeg",
    "yunnan-gallery-img-13": "images/whatsapp_imports/wa_1781335386_ooku3.jpeg",
    "yunnan-gallery-img-14": "images/whatsapp_imports/wa_1781335386_ziu5d.jpeg",
    "yunnan-gallery-img-15": "images/whatsapp_imports/wa_1781335387_ue55e.jpeg",
    "yunnan-gallery-img-16": "images/whatsapp_imports/wa_1781335387_w6lyg.jpeg",
    "yunnan-gallery-img-17": "images/whatsapp_imports/wa_1781335388_d3gtf.jpeg",
    "yunnan-gallery-img-18": "images/whatsapp_imports/wa_1781335389_hbops.jpeg",
    "yunnan-gallery-img-19": "images/whatsapp_imports/wa_1781335389_qqvf3.jpeg",
    "yunnan-gallery-img-20": "images/whatsapp_imports/wa_1781335390_79wm1.jpeg",
    "yunnan-gallery-img-21": "images/whatsapp_imports/wa_1781335390_9gpe6.jpeg",
    "yunnan-gallery-img-22": "images/whatsapp_imports/wa_1781335390_nh66e.jpeg",
    "yunnan-gallery-img-23": "images/whatsapp_imports/wa_1781335391_eywaf.jpeg",
    "yunnan-gallery-img-24": "images/whatsapp_imports/wa_1781335391_lkte8.jpeg",
    "yunnan-gallery-img-25": "images/whatsapp_imports/wa_1781335391_t5743.jpeg",
    "yunnan-gallery-img-26": "images/whatsapp_imports/wa_1781335392_6o8j9.jpeg",
    "yunnan-gallery-img-27": "images/whatsapp_imports/wa_1781335393_29b3u.jpeg",
    "yunnan-gallery-img-28": "images/whatsapp_imports/wa_1781335393_50wf4.jpeg",
    "yunnan-gallery-img-29": "images/whatsapp_imports/wa_1781335393_ahs6i.jpeg",
    "yunnan-gallery-img-30": "images/whatsapp_imports/wa_1781335394_4600y.jpeg",
    "yunnan-gallery-img-31": "images/whatsapp_imports/wa_1781335394_gc32o.jpeg",
    "yunnan-gallery-img-32": "images/whatsapp_imports/wa_1781335394_lqq0x.jpeg",
    "yunnan-gallery-img-33": "images/whatsapp_imports/wa_1781335395_131an.jpeg",
    "yunnan-gallery-img-34": "images/whatsapp_imports/wa_1781335395_u82rq.jpeg",
    "yunnan-gallery-img-35": "images/whatsapp_imports/wa_1781335396_037kn.jpeg",
    "yunnan-gallery-img-36": "images/whatsapp_imports/wa_1781335396_29ryi.jpeg",
    "yunnan-gallery-img-37": "images/whatsapp_imports/wa_1781335396_ybokn.jpeg",
    "yunnan-gallery-img-38": "images/whatsapp_imports/wa_1781335397_drvmq.jpeg"
  }
};
